language:
  - python

python:
  - 2.7

install:
  # google app engine
  - curl -O https://googleappengine.googlecode.com/files/google_appengine_1.8.9.zip
  - unzip -q google_appengine_1.8.9.zip
  # mock
  - pip install -U mock

before_script:
  - node -v

script:
  - python test.py